# Generated by Django 4.0 on 2021-12-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll',
            field=models.CharField(choices=[('owner', 'owner'), ('manager', 'manger')], default='owner', max_length=10),
        ),
    ]
